[package]
name = "ad4-lang"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"
nursery = "warn"

[dependencies]
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0.12"
