[lib]
proc-macro = true

[package]
name = "macros"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
syn = { version ="2.0.101" }
quote = "1.0.40"
proc-macro2 = "1"

[lints]
workspace = true
